#!/bin/bash                                                                                                                                              
for file in ./*                                                                                                                                          
do chmod u+x $file                                                                                                                                       
done

